- name : softeares
  hosts : native
  connection : local
  tasks:
  - name : installing softwares using loops 
    ansible.builtin. package:
      name : "{{ item }}"
      state : latest
    loop :
    - nginx
    - python3
    - mysql
  