- name : functions
  hosts : native
  connection: local
  vars:
  skills: Devops,Linux,Shell-scripting,Ansible,terraform
  tasks : 
  - name : default function
    ansible.builtin.debug:
      msg : "name is :{{name | default ('Ramesh')}}"    
