- name : error handling 
  hosts : native
  connection : local 
  become : yes
  tasks:
  - name : checking roboshop user
    ansible.builtin.command: id roboshop
    register : user_output
    ignore_errors: true
    
  - name : creating roboshop user 
    ansible.builtin.command: useradd roboshop
    when : user_outpu.rc != 0
  